### ISSUE TITLE
Documentation Incomplete

### ISSUE THREAD

**Issue by sayemoid** [noman404/BanglaTextView#2]
Hi,

I was trying to implement it for a date but couldn't find a way to use it from the documentation. I thiink it should be more clear about the inputs it takes.

For instance when I provide a string containing a date, It doesn't convert it to bengali. 

if I have to input a string then there should be documentation for it (Which date/number/distance format I've to provide)

Heres the code
**in xml**
```
<com.al.tobangla.views.BNTextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/txtAvailableFromBn"
                    app:processType="date" />
```
**java**
```
BNTextView txtAvailableFromBn = findViewById(R.id.txtAvailableFromBn);
        txtAvailableFromBn.setText("May 2018");
```

**Comment by noman404** [comment]
**"May 2018"** pattern is not supporting in the current implementation. You may try for the certain date or certain month. For now to achieve that, try [this](https://github.com/noman404/BanglaTextView/blob/af2bd681c3a8b3be27e66c86469a3b29969d69ac/tobangla/src/main/java/com/al/tobangla/processor/ToBN.java#L184) + getNumber(YOUR_YEAR), by using `ToBN.getInstance()...`

To get a simple date in any pattern TheBNTextView.setText("1952/02/21"); will simple works as provided in the sample app. Have a look there.
