### ISSUE TITLE
Sync problem 

### ISSUE THREAD

**Issue by Soyeb189** [noman404/BanglaTextView#4]
ERROR: Failed to resolve: com.github.noman404:BanglaTextView:1.0.6
Show in Project Structure dialog
Affected Modules: app

**Comment by noman404** [comment]
Please post the whole log.

**Comment by Soyeb189** [comment]
![Capture2](https://user-images.githubusercontent.com/20877836/55169686-6b199780-519f-11e9-9a44-03e4ff07e248.PNG)

You have done a great job but i can not download it.

**Comment by Soyeb189** [comment]
The problem is solved 
I have missed to add  maven { url 'https://jitpack.io' }
